export { default as Menu } from './Menu'
export { default as Navbar } from './Navbar'
export { default as Slider } from './Slider'
export { default as Traits } from './Traits'
export { default as Services } from './Services'
export { default as Projects } from './Projects'
